const code=document.getElementById('code'),result=document.getElementById('result'),treeOut=document.getElementById('treeOut');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function lines(){return code.value.split('\n').map((raw,i)=>({n:i+1,raw,trim:raw.trim()})).filter(x=>x.trim)}
function concepts(line){const out=[];if(/^def\s+/.test(line))out.push('Function');if(/return\b/.test(line))out.push('Return value');if(/if\b/.test(line))out.push('Condition');if(/[=*+\-/]/.test(line))out.push('Expression');if(/None|null/.test(line))out.push('Null check');return out.length?out:['Code logic']}
function explain(){result.innerHTML=lines().map(l=>`<div class="card"><span>Line ${l.n}</span><code>${esc(l.raw)}</code><p><b>What:</b> ${what(l.trim)}</p><p><b>Why:</b> ${why(l.trim)}</p><p><b>Common mistake:</b> ${mistake(l.trim)}</p></div>`).join('')||'<p>Paste code first.</p>'}
function what(t){if(/^def\s+/.test(t))return 'Creates a reusable function.';if(/^if\b/.test(t))return 'Checks a condition before continuing.';if(/^return\b/.test(t))return 'Sends a value back to the caller.';if(/=/.test(t))return 'Stores or calculates a value.';return 'Runs one step of program logic.'}
function why(t){if(/^def\s+/.test(t))return 'The developer grouped logic so it can be reused and explained clearly.';if(/^if\b/.test(t))return 'It protects the program from unsafe or unwanted cases.';if(/^return\b/.test(t))return 'Without a return, the caller may not receive the final result.';if(/=/.test(t))return 'It gives the program a named value to use later.';return 'It moves the program toward the intended outcome.'}
function mistake(t){if(/^def\s+/.test(t))return 'Forgetting parameters or indentation.';if(/^if\b/.test(t))return 'Only testing the happy path and missing empty values.';if(/^return\b/.test(t))return 'Printing instead of returning when another function needs the value.';return 'Reading syntax without asking what job the line performs.'}
function whyMode(){const selected=code.value.substring(code.selectionStart,code.selectionEnd).trim()||lines()[0]?.trim||'';result.innerHTML=`<div class="card"><span>WHY MODE</span><h3>${esc(selected||'Developer intent')}</h3><p>${esc(why(selected))}</p><p><b>If removed:</b> The program may still run, but it loses safety, clarity, or the final output path.</p></div>`}
function tree(){const all=[...new Set(lines().flatMap(l=>concepts(l.trim)))];treeOut.innerHTML='<div class="node root"><b>Your code</b><p>Static concept map generated in the browser.</p></div>'+all.map(c=>`<div class="node">${esc(c)}</div>`).join('')}
document.getElementById('explain').onclick=explain;document.getElementById('why').onclick=whyMode;document.getElementById('tree').onclick=tree;explain();tree();